application: talma-bookmarklets
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /teste.html
  static_files: teste.html
  upload: teste.html

- url: /testesUnit.js
  static_files: testesUnit.js
  upload: testesUnit.js

- url: /.*
  script: main.app